<?php return array(
    'root' => array(
        'name' => 'cakephp/app',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'brick/varexporter' => array(
            'pretty_version' => '0.3.8',
            'version' => '0.3.8.0',
            'reference' => 'b5853edea6204ff8fa10633c3a4cccc4058410ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/varexporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/app' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/bake' => array(
            'pretty_version' => '2.9.3',
            'version' => '2.9.3.0',
            'reference' => 'a9b02fb6a5f96e8fb9887be55cccea501468907b',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/bake',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/cakephp' => array(
            'pretty_version' => '4.6.4',
            'version' => '4.6.4.0',
            'reference' => '70b5c1097866f7f392d052ab4514c9705449fb3f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cakephp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/chronos' => array(
            'pretty_version' => '2.4.5',
            'version' => '2.4.5.0',
            'reference' => 'b0321ab7658af9e7abcb3dd876f226e6f3dbb81f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/chronos',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/collection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/datasource' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/debug_kit' => array(
            'pretty_version' => '4.10.3',
            'version' => '4.10.3.0',
            'reference' => '5e0fe27721e220d1b1104108edcaf793e98307c0',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/debug_kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/event' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/i18n' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/migrations' => array(
            'pretty_version' => '3.9.0',
            'version' => '3.9.0.0',
            'reference' => '58446fdd096087ddf7752c0317731b8725d1dc28',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/orm' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/plugin-installer' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'e27027aa2d3d8ab64452c6817629558685a064cb',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cakephp/plugin-installer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/twig-view' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'e4a18e91e004730ccbaf796bde60612e8afac0e8',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/twig-view',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'cakephp/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.6.4',
            ),
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.5.12',
            'version' => '1.5.12.0',
            'reference' => '00a2f4201641d5c53f7fc0195e6c8d9fcc321a78',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/class-map-generator' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => '86d8208fc3c649a3a999daf1a63c25201be2990f',
            'type' => 'library',
            'install_path' => __DIR__ . '/./class-map-generator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.10.1',
            'version' => '2.10.1.0',
            'reference' => '4120703b9bda8795075047b40361d7ec4d2abe49',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'd5a341b3fb61f3001970940afb1d332968a183ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'reference' => '198166618906cb2de69b95d7d47e5fa8aa1b2b95',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '5ecd0cb4177696f9fd48f1605dda81db3dee7889',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'reference' => '6c1925561632e83d60a44492e0b344cf48ab85ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '3447381095d32a171fe3a58323749f44dbb5ac7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jasny/twig-extensions' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => '8a5ca5f49317bf421a519556ad2e876820d41e01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasny/twig-extensions',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '6.10.0',
            'version' => '6.10.0.0',
            'reference' => '8b1308a9d7bdbdb20ce87ef920f82b4564bb2d33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laminas/laminas-diactoros' => array(
            'pretty_version' => '2.17.0',
            'version' => '2.17.0.0',
            'reference' => '5b32597aa46b83c8b85bb1cf9a6ed4fe7dd980c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-diactoros',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-httphandlerrunner' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'eb670c5c7167cd218c61a8b4f6ab9ce339200c16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-httphandlerrunner',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.5',
            'version' => '4.2.5.0',
            'reference' => 'd3cebb0ff4685ff61c749e54b27db49319e2ec00',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'marc-mabe/php-enum' => array(
            'pretty_version' => 'v4.7.2',
            'version' => '4.7.2.0',
            'reference' => 'bb426fcdd65c60fb3638ef741e8782508fda7eef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../marc-mabe/php-enum',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.47',
            'version' => '2.8.47.0',
            'reference' => '28e9045958dcaf771f9b56564549d5b174e38b0e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.19.5',
            'version' => '4.19.5.0',
            'reference' => '51bd93cc741b7fc3d63d20b6bdcd99fdaa359837',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
                1 => '^1.0 || ^2.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-server-handler' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '84c4fb66179be4caaf8e97bd239203245302e7d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-server-handler-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-server-middleware' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'c1481f747daaa6a0782775cd6a8c26a1bf4a3829',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-middleware',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-server-middleware-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
                1 => '^1.0 || ^2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0 || ^2.0',
            ),
        ),
        'react/promise' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'reference' => '23444f53a813a3296c1368bb104793ce8d88f04a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'robmorgan/phinx' => array(
            'pretty_version' => '0.13.4',
            'version' => '0.13.4.0',
            'reference' => '18e06e4a2b18947663438afd2f467e17c62e867d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../robmorgan/phinx',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'reference' => '9a90eb5d32d5a500296bf43f946d60246444d5f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/signal-handler' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '04a6112e883ad76c0ada8e4a9f7520bbfdb6bb98',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/signal-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v5.4.46',
            'version' => '5.4.46.0',
            'reference' => '977c88a02d7d3f16904a81907531b19666a08e78',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.47',
            'version' => '5.4.47.0',
            'reference' => 'c4ba980ca61a9eb18ee6bcc73f28e475852bb1ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.4',
            'version' => '2.5.4.0',
            'reference' => '605389f2a7e5625f273b53960dc46aeaf9c62918',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v5.4.45',
            'version' => '5.4.45.0',
            'reference' => '57c8294ed37d4a055b77057827c67f9558c95c54',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.4.45',
            'version' => '5.4.45.0',
            'reference' => '63741784cd7b9967975eec610b256eed3ede022b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '141046a8f9477948ff284fa65be2095baafb94f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => 'e9247d281d694a5120554d9afaf54e070e88a603',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.38.0',
            'version' => '1.38.0.0',
            'reference' => '2d446c214bdbe5b71bde5011b060a05fece3ae6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.38.2',
            'version' => '1.38.2.0',
            'reference' => 'd3d318bad5e7a1bfbd026009c8bfb8d8f99ae6b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '0f68c03565dcaaf25a890667542e8bd75fe7e5bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => 'dfb55726c3a76ea3b6459fcfda1ec2d80a682411',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => '6bfb9c766cacffbc8e118cb87217d08ed84e5cd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php84' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => 'f4e1dfaee5b74aba5964fe1fd4dfc7ba5e3085fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php84',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.4.51',
            'version' => '5.4.51.0',
            'reference' => '467bfc56f18f5ef6d5ccb09324d7e988c1c0a98f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '191afdcb5804db960d26d8566b7e9a2843cab3a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.4.47',
            'version' => '5.4.47.0',
            'reference' => '136ca7d72f72b599f2631aca474a4f8e26719799',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/markdown-extra' => array(
            'pretty_version' => 'v3.11.0',
            'version' => '3.11.0.0',
            'reference' => '504557d60d80478260ebd2221a2b3332a480865d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/markdown-extra',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.11.3',
            'version' => '3.11.3.0',
            'reference' => '3b06600ff3abefaf8ff55d5c336cd1c4253f8c7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
