NR==377954 {
  print "-- --------------------------------------------------------";
  print "";
  print "--";
  print "-- Table structure for table `schedulingeventtweaks`";
  print "--";
  print "";
  print "CREATE TABLE `schedulingeventtweaks` (";
  print "  `id` bigint(20) NOT NULL,";
  print "  `conventionseasons_id` bigint(20) NOT NULL,";
  print "  `event_id` bigint(20) NOT NULL,";
  print "  `pinned_day` varchar(32) DEFAULT NULL,";
  print "  `pinned_room_id` bigint(20) DEFAULT NULL,";
  print "  `pinned_start_time` time DEFAULT NULL,";
  print "  `available_from_time` time DEFAULT NULL,";
  print "  `available_to_time` time DEFAULT NULL,";
  print "  `created` datetime DEFAULT NULL,";
  print "  `modified` datetime DEFAULT NULL";
  print ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
  print "";
  print "--";
  print "-- Indexes for table `schedulingeventtweaks`";
  print "--";
  print "ALTER TABLE `schedulingeventtweaks`";
  print "  ADD PRIMARY KEY (`id`),";
  print "  ADD UNIQUE KEY `uniq_set_convention_event` (`conventionseasons_id`,`event_id`),";
  print "  ADD KEY `idx_set_conventionseasons_id` (`conventionseasons_id`),";
  print "  ADD KEY `idx_set_event_id` (`event_id`);";
  print "";
  print "-- --------------------------------------------------------";
  print "";
  print "--";
  print "-- Table structure for table `schedulingroomlimits`";
  print "--";
  print "";
  print "CREATE TABLE `schedulingroomlimits` (";
  print "  `id` bigint(20) NOT NULL,";
  print "  `conventionseasons_id` bigint(20) NOT NULL,";
  print "  `room_id` bigint(20) NOT NULL,";
  print "  `day` varchar(32) NOT NULL,";
  print "  `max_hours` decimal(6,2) DEFAULT NULL,";
  print "  `created` datetime DEFAULT NULL,";
  print "  `modified` datetime DEFAULT NULL";
  print ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
  print "";
  print "--";
  print "-- Indexes for table `schedulingroomlimits`";
  print "--";
  print "ALTER TABLE `schedulingroomlimits`";
  print "  ADD PRIMARY KEY (`id`),";
  print "  ADD UNIQUE KEY `uniq_srl_convention_room_day` (`conventionseasons_id`,`room_id`,`day`),";
  print "  ADD KEY `idx_srl_conventionseasons_id` (`conventionseasons_id`),";
  print "  ADD KEY `idx_srl_room_id` (`room_id`);";
  print "";
}
NR==378144 {
  print "--";
  print "-- AUTO_INCREMENT for table `schedulingeventtweaks`";
  print "--";
  print "ALTER TABLE `schedulingeventtweaks`";
  print "  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;";
  print "";
  print "--";
  print "-- AUTO_INCREMENT for table `schedulingroomlimits`";
  print "--";
  print "ALTER TABLE `schedulingroomlimits`";
  print "  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;";
  print "";
}
{ print }
